name: Test
on:
  push:
    branches: [ "master" ]
  pull_request_target:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
jobs:
  build-library:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests (native-tls)
        run: cargo test --verbose
      - name: Run tests (rustls)
        run: cargo test --verbose --no-default-features --features=rustls
  build-examples:
    name: Build examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Build examples
        # TODO: build all examples with a single command?
        run: |
          cargo build --example chat_cli
          cargo build --example chat_stream_cli
          cargo build --example completions_cli
